apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: echo
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Hello, World!'; sleep 10; done"]
